<? /** @var $block array */ ?><?

global $arTheme;
global $APPLICATION;

global $sprintSearchFilter;
$sprintSearchFilter = array(
    "=ID" => $block['element_ids'],
);

?>
<?php if (!empty($block['element_ids'])) ?>
    <? $APPLICATION->IncludeComponent(
        "bitrix:catalog.section",
        'catalog_blockcolors_slide_editor',
        Array(
            "IBLOCK_TYPE" => 'aspro_next_catalog',
            "IBLOCK_ID" => $block['iblock_id'],

            "ELEMENT_SORT_FIELD" => "SORT",
            "ELEMENT_SORT_ORDER" => "asc",
            "FILTER_NAME" => "sprintSearchFilter",

            "SHOW_ALL_WO_SECTION" => "Y",
            "SECTION_ID" => '',
            "SECTION_CODE" => '',

            "USE_REGION" => "N",
          	"STORES" => "",
		"SHOW_UNABLE_SKU_PROPS" => "Y",
		"AJAX_REQUEST" => "N",
		"INCLUDE_SUBSECTIONS" => "N",
		"PAGE_ELEMENT_COUNT" => "20",
		"LINE_ELEMENT_COUNT" => "4",
		"TYPE_SKU" => $arTheme["TYPE_SKU"]["VALUE"],
		"PROPERTY_CODE" => array(
		0 => "MINIMUM_PRICE",
			1 => "MAXIMUM_PRICE",
			2 => "HIT",
			3 => "BRAND",
			4 => "PROP_2065",
			5 => "POPUP_VIDEO",
			6 => "CML2_ARTICLE",
			7 => "ASSOCIATED",
			8 => "PROP_2052",
			9 => "SET",
			10 => "UNIT_KOEF",
			11 => "BASE_KOEF",
			12 => "COLOR_MAIN_EL",
			13 => "USAGE_DOSKA_DPK",
			14 => "ATTRIBUTES",
			15 => "TOLSHINA",
			16 => "PROP_2083",
			17 => "CML2_LINK",
			18 => "DECKING_PROFILE",
			19 => "COLOR_REF2",
			20 => "",
		),
		"SHOW_ARTICLE_SKU" => "N",
		"SHOW_MEASURE_WITH_RATIO" => "N",
		"OFFERS_FIELD_CODE" => array(
			0 => "NAME",
			1 => "CML2_LINK",
			2 => "DETAIL_PAGE_URL",
			3 => "",
		),
		"OFFERS_PROPERTY_CODE" => array(
		0 => "VID",
			1 => "DLINA_STR",
			2 => "WIDTH",
			3 => "THICK",
			4 => "VES",
			5 => "MATERIAL",
			6 => "GARANTY",
			7 => "ARTICLE",
			8 => "VWS_N",
			9 => "DLINA",
			10 => "UNIT_KOEF",
			11 => "MODEL_OP",
			12 => "MONTAZ_PAZ",
			13 => "NORM",
			14 => "VALUE_TOV",
			15 => "BASE_KOEF",
			16 => "RAZM",
			17 => "SVET",
			18 => "TYPE_PRODUCTS",
			19 => "PRODUCT_VIDEO",
			20 => "TYPE",
			21 => "DECKING_PROFILE",
			22 => "TSVET_OGRAZHDENIY",
			23 => "WIDTH_D",
			24 => "TOLSHINA",
			25 => "",

		),
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_FIELD2" => "name",
		"OFFERS_SORT_ORDER2" => "asc",
		"OFFER_TREE_PROPS" => array(
			0 => "SIZES",
			1 => "COLOR_REF",
			2 => "DLINA",
		),
		"OFFERS_LIMIT" => "300",
		"SECTION_URL" => "",
		"DETAIL_URL" => "",
		"BASKET_URL" => "/basket/",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SET_LAST_MODIFIED" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "N",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "N",
		"CACHE_TIME" => "3600000",
		"CACHE_GROUPS" => "N",
		"CACHE_FILTER" => "Y",
		"META_KEYWORDS" => "-",
		"META_DESCRIPTION" => "-",
		"BROWSER_TITLE" => "-",
		"ADD_SECTIONS_CHAIN" => "N",
		"HIDE_NOT_AVAILABLE" => "N",
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"DISPLAY_COMPARE" => "N",
		"SET_TITLE" => "N",
		"SET_STATUS_404" => "N",
		"SHOW_404" => "N",
		"MESSAGE_404" => "",
		"PRICE_CODE" => array(
			0 => "BASE",
		),
		"USE_PRICE_COUNT" => "Y",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"USE_PRODUCT_QUANTITY" => "Y",
		"OFFERS_CART_PROPERTIES" => array(
			0 => "DLINA",
		),
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"PAGER_TITLE" => "Товары",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "main",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"ADD_CHAIN_ITEM" => "N",
		"SHOW_QUANTITY" => "Y",
		"SHOW_QUANTITY_COUNT" => "Y",
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"SHOW_DISCOUNT_TIME" => "N",
		"SHOW_OLD_PRICE" => "Y",
		"CONVERT_CURRENCY" => "Y",
		"CURRENCY_ID" => "RUB",
		"USE_STORE" => "N",
		"MAX_AMOUNT" => "20",
		"MIN_AMOUNT" => "10",
		"USE_MIN_AMOUNT" => "N",
		"USE_ONLY_MAX_AMOUNT" => "Y",
		"DISPLAY_WISH_BUTTONS" => "N",
		"LIST_DISPLAY_POPUP_IMAGE" => "Y",
		"DEFAULT_COUNT" => "1",
		"SHOW_MEASURE" => "Y",
		"SHOW_HINTS" => "Y",
		"OFFER_HIDE_NAME_PROPS" => "N",
		"SECTIONS_LIST_PREVIEW_PROPERTY" => "UF_SECTION_DESCR",
		"SHOW_SECTION_LIST_PICTURES" => "Y",
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PARTIAL_PRODUCT_PROPERTIES" => "Y",
		"PRODUCT_PROPERTIES" => array(
		),
		"SALE_STIKER" => "SALE_TEXT",
		"STIKERS_PROP" => "HIT",
		"SHOW_RATING" => "N",
		"COMPONENT_TEMPLATE" => "catalog_blockcolors_slide_editor",
		"SECTION_USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"CUSTOM_FILTER" => "{\"CLASS_ID\":\"CondGroup\",\"DATA\":{\"All\":\"AND\",\"True\":\"True\"},\"CHILDREN\":[]}",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER2" => "desc",
		"BACKGROUND_IMAGE" => "-",
		"SEF_MODE" => "N",
		"SET_BROWSER_TITLE" => "Y",
		"SET_META_KEYWORDS" => "Y",
		"SET_META_DESCRIPTION" => "Y",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"COMPATIBLE_MODE" => "Y",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N"
	),
	$component,
	array(
		"HIDE_ICONS" => $isAjax
	)
); ?>
