<?
/* Копия km_akciya.php под новый дизайн: те же параметры выборки,
   отличается только шаблон вывода — баннер справа от плиток подразделов. */
global $arFilterActiya;
$arFilterActiya = array("PROPERTY_LINK_SECT_CATALOG" => $arSection["ID"], "PROPERTY_LINK_REGION" => $regionID, "ACTIVE" => "Y", "ACTIVE_DATE" => "Y");
?>

<?$GLOBALS["arLandingTizers"] = array("ID" => $arSeoItem["PROPERTY_LINK_SECT_CATALOG"],);?>
<?$APPLICATION->IncludeComponent(
	"bitrix:news.list",
	"akciya_catalog_sections_newdesign",
	[
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		// AJAX_MODE обязательно N: с "Y" компонент внутри ob_start() рвёт наш
		// буфер (ajax-обёртка закрывает его и открывает свой), и разметка
		// баннера уезжает мимо ряда с подразделами.
		"AJAX_MODE" => "N",
		"IBLOCK_TYPE" => "aspro_next_content",
		"IBLOCK_ID" => "17",
		"NEWS_COUNT" => "4",
		"SORT_BY1" => "SORT",
		"SORT_ORDER1" => "ASC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"FILTER_NAME" => "arFilterActiya",
		"FIELD_CODE" => [
			0 => "ID",
			1 => "NAME",
			2 => "PREVIEW_TEXT",
			3 => "PREVIEW_PICTURE",
			4 => "DATE_ACTIVE_FROM",
			5 => "ACTIVE_FROM",
			6 => "DATE_ACTIVE_TO",
			7 => "",
		],
		"PROPERTY_CODE" => [
			0 => "PERIOD",
			1 => "DESCRIPTION",
			2 => "LINK_SECT_CATALOG",
			3 => "LINK_REGION",
			4 => "",
		],
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"SET_TITLE" => "Y",
		"SET_BROWSER_TITLE" => "Y",
		"SET_META_KEYWORDS" => "Y",
		"SET_META_DESCRIPTION" => "Y",
		"SET_LAST_MODIFIED" => "Y",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"HIDE_LINK_WHEN_NO_DETAIL" => "Y",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"INCLUDE_SUBSECTIONS" => "Y",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "3600",
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"PAGER_TITLE" => "Новости",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SET_STATUS_404" => "",
		"SHOW_404" => "",
		"MESSAGE_404" => "",
		"PAGER_BASE_LINK" => "",
		"PAGER_PARAMS_NAME" => "arrPager",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"COMPONENT_TEMPLATE" => "akciya_catalog_sections_newdesign",
		"STRICT_SECTION_CHECK" => "Y",
		"FILE_404" => "",
		"IMAGE_POSITION" => "left",
		"SHOW_DETAIL_LINK" => "Y",
		"USE_SHARE" => "N",
		"S_ASK_QUESTION" => "",
		"S_ORDER_SERVICE" => "",
		"T_GALLERY" => "",
		"T_DOCS" => "",
		"T_GOODS" => "",
		"T_SERVICES" => "",
		"T_PROJECTS" => "",
		"T_REVIEWS" => "",
		"T_STAFF" => ""
	],
	false
);?>
